---
# Docker-based Test Kitchen configuration using Dokken
driver:
  name: dokken
  privileged: true
  chef_version: latest
  chef_license: accept-no-persist

transport:
  name: dokken

provisioner:
  name: dokken
  chef_license: accept-no-persist
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true
  log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo

  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo

  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo

  - name: rockylinux-9
    driver:
      image: dokken/rockylinux-9
      pid_one_command: /usr/lib/systemd/systemd

  - name: almalinux-9
    driver:
      image: dokken/almalinux-9
      pid_one_command: /usr/lib/systemd/systemd

  - name: amazonlinux-2023
    driver:
      image: dokken/amazonlinux-2023
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[zabbix::default]
    verifier:
      inspec_tests:
        - test/integration/default

  - name: agent
    run_list:
      - recipe[zabbix::agent]
    verifier:
      inspec_tests:
        - test/integration/agent
